### ISSUE TITLE
Gameplay | Dodanie Rund

### ISSUE THREAD

**Issue by jkisicki** [blenik/keysGame#13]
Dodanie rund:

gra konczy się gdy jeden z graczy osiągnie 3 zwycięstwa rund.
Wynik rund powinien być wyświetlany w odpowiednim, przygotowanym już do tego miejscu.

**Comment by Hary393** [comment]
Przypadkiem zrobiłem to razem z możliwością wygrania gry.
Nie wiedziałem że to osobny issue.
